before_install:
  - brew update > /dev/null
  - brew install p7zip
  - brew outdated p7zip || brew upgrade p7zip
  - wget https://bintray.com/artifact/download/oracle-jdk/generic/jdk-8u72-macosx-x64.zip
  - 7z -ojdk8 x jdk-8u72-macosx-x64.zip  
  - export JAVA_HOME=jdk8/Contents/Home

language: java

os:
  - osx
  
script: mvn -Dbintray_token=$bintray_token clean compile exec:java